version: '3.4'
services:
  frontend:
    image: frontend
    container_name: front-chat
    ports:
      - 3001:3000
    depends_on:
    - backend
  backend:
      image: backend
      container_name: back-chat